name: Navidrome CI

on:
  workflow_dispatch: {}

env:
  APP_NAME: navidrome
  APP_VERSION: v0.59.0
  APP_REPO: https://github.com/navidrome/navidrome
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/navidrome

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare app sources
        run: |
          git clone --branch ${{ env.APP_VERSION }} ${{ env.APP_REPO }} ${{ env.APP_NAME }}
          pushd ${{ env.APP_NAME }}
            # Replace base image since orinigal does not have RISC-V version
            sed -i s%public.ecr.aws/docker/library/alpine:3.19%alpine:3.19%g Dockerfile
          popd

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/riscv64
          context: ${{ env.APP_NAME }}
          file: ${{ env.APP_NAME }}/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.APP_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
